##(13)Permission denied: access to / denied

```
# setenforce 0
# vi /etc/selinux/config

SELINUX=permissive
```

(記録: 2014-07-15)

##received a naive datetime (...) while time zone support is active.

Django の DateTimeField に datetime.datetime.now() を保管していると下記のようなメッセージが出ることがあるが、

```
[04/Sep/2014 11:53:51] "POST /chat/ HTTP/1.1" 200 3563
/usr/lib/python2.6/site-packages/Django-1.6.5-py2.6.egg/django/db/models/fields/__init__.py:903: RuntimeWarning: DateTimeField ChatMessage.time_posted received a naive datetime (2014-09-04 11:53:57.364472) while time zone support is active.
  RuntimeWarning)
```

正しくは django.utils.timezone.now() を用いるようだ。

(記録: 2014-09-04)

##attempt to write a readonly database

Apache で Django アプリケーションを動かしている際に db.sqlite3 を更新できずに落ちる。所有者が root:root だったので apache:apache に変更した。
